package ch6java6thedition;
import java.util.Scanner;
/**
 * This is the fishing game simulation problem corresponding
 * to number 18 in the programming challenges. In this game,
 * a six-sided die is rolled to determine what the player
 * has caught. Each possible item is worth a certain number
 * of fishing points. The points will remain hidden until 
 * the user is finished fishing, and then a message is 
 * displayed congratulating the user, depending on the number
 * of fishing points gained. 
 * 
 * Here are some suggestions for the game's design:
 * 
 * - Each round of the game is performed as an iteration of
 *   a loop that repeats as long as the player wants to keep
 *   fishing. 
 * - At the beginning of each round, the program will ask the
 *   user whether or not he or she wants to keep fishing. 
 * - The program simulates the rolling of a six-sided die (use
 *   the DieRoller class).
 * - Each item that can be caught is represented by a number
 *   generated by the die; for example, 1 for "a huge fish", 
 *   2 for "an old shoe", 3 for "a little fish", and so on. 
 * - The loop keeps a running total of the player's points. 
 * - After the loop has finished, the total amount of fishing 
 *   points is displayed, along with a message that varies 
 *   according to the amount of points earned. 
 * @author craig
 */
public class FishingGameSimulation {
	public static void main(String [] args) {
		// Variables
		String answer;
		int totalScore = 0;

		// Create a Scanner object
		Scanner input = new Scanner(System.in);
	
		// Explain what this is about 
		System.out.println("This is a fishing game. It will continue until"
			+ " you want to quit.\nYou will catch things. You will "
			+ "get points. You'll love it and want to continue forever.");
		System.out.println("Ready to begin?");
		answer = input.nextLine();

		while(answer.equals("Y") || answer.equals("y")) {
			// Create a DieRoller object
			DieRoller die = new DieRoller(6);
			die.roll();

			if(die.getValue() == 1) {
				System.out.println("You caught a HUGE fish! "
					+ "That's 50 points!");
				totalScore += 50;
			} else if(die.getValue() == 2) {
				System.out.println("You caught an old shoe. "
					+ "Congratulations... 0 points");
			} else if(die.getValue() == 3) {
				System.out.println("You caught a medium sized fish. "
					+ "25 points.");
				totalScore += 25;
			} else if(die.getValue() == 4) {
				System.out.println("You caught a toilet lid..."
					+ "that's actually 7 points xD");
				totalScore += 7;
			} else if(die.getValue() == 5) {
				System.out.println("You caught a small fish. "
					+ "That's 15 points.");
				totalScore += 15;
			} else {
				System.out.println("You caught a mermaid!!! "
					+ "That's 100 points!");
				totalScore += 100;
			}

			System.out.println("Wanna keep fishing?");
			answer = input.nextLine();
		}
		System.out.println("Your total score is " + totalScore 
		+ "\nThanks for playing!");
	}			
}
